### ISSUE TITLE
Tips to determine endpoint_id?

### ISSUE THREAD

**Issue by thbar** [membraneframework/membrane_portaudio_plugin#9]
Thanks for Membrane! I'm trying it out to record iPad audio (which is exposed as an input soundcard when connected over a lightning cable to a Mac) and send it to the default soundcard output, as a starter.

I believe I will need to specify a `endpoint_id` to the source, because the iPad audio is not the default input.

Do you have an easy way to figure out what the ids are? Thank you!

**Comment by mat-hek** [comment]
Hi @thbar , you're welcome :) Unfortunately I don't know if there is a universal way of recognizing an assignment of `device_id` (that  `endpoint_id` maps to in PortAudio) to the particular hardware. Moreover, afaik it can differ e.g. depending on order soundcards are connected... Anyway, you can check out http://portaudio.com/docs/v19-doxydocs/querying_devices.html . BTW, maybe it would be good to make it a mix task.

**Comment by thbar** [comment]
Thank you! I will work on a PR to expose that as a helper method (& yes a mix task that would display the results is a good idea!).

**Comment by mat-hek** [comment]
Great! You can check first if this gives you any useful information ;) Also please note we use [unifex](https://github.com/membraneframework/unifex/) for the native parts of the framework. If you had any questions we're here to help.

**Comment by thbar** [comment]
I've seen that and also discovered bundlex, so this will be a great way to have a first hands-on case for their use. Thanks!

**Comment by lawik** [comment]
So there is currently not any convenience functionality in this module to get a list of devices? It would be nice to have that or have a library for some of those common audio-recording tasks in Elixir. Is this something y'all working with Membrane have and could expose?

**Comment by mat-hek** [comment]
Hi @lawik, unfortunately, we don't have this functionality, but we're open for PRs ;)

**Comment by lawik** [comment]
Fair enough. If I end up doing a specific project I might end up needing to do just that :)
